// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RemesasApp.Data;

#nullable disable

namespace RemesasApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241005031206_SecondM")]
    partial class SecondM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RemesasApp.Models.ConversionMoneda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("TasaBtcUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TasaUsdBtc")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ConversionMonedas");
                });

            modelBuilder.Entity("RemesasApp.Models.Remesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EstadoTransaccion")
                        .HasColumnType("text");

                    b.Property<string>("MonedaEnviada")
                        .HasColumnType("text");

                    b.Property<decimal?>("MontoEnviado")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MontoFinal")
                        .HasColumnType("numeric");

                    b.Property<string>("NombreDestinatario")
                        .HasColumnType("text");

                    b.Property<string>("NombreRemitente")
                        .HasColumnType("text");

                    b.Property<string>("PaisDestino")
                        .HasColumnType("text");

                    b.Property<string>("PaisOrigen")
                        .HasColumnType("text");

                    b.Property<decimal?>("TasaCambio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Remesas");
                });
#pragma warning restore 612, 618
        }
    }
}
